default:
  server:
    port: 3000
  database:
    host: '127.0.0.1'
    port: 6379
    db: 0
  filedir: '/home/wesley/Data'
  scale: 500
development:
  database:
    db: 'dev_db'
test:
  database:
    db: 'test_db'
production:
  server:
    port: 3000
  database:
    host: '127.0.0.1'
    port: 6379
    db: 0
  filedir: '/home/wesley/Data'
  scale: 500
